### ISSUE TITLE
Help Config!

### ISSUE THREAD

**Issue by jtrent238** [tterrag1098/CustomThings#13]
I Need Help Config!

**Comment by tterrag1098** [comment]
Good for you. Did you even read the wiki?

**Comment by jtrent238** [comment]
Yes But I Cant Figure It Out!

**Comment by tterrag1098** [comment]
Could you be more specific? What do you need help with? What is causing you problems? I can't do anything with "I can't figure it out".

**Comment by jtrent238** [comment]
I Dont Know How To Setup

**Comment by tterrag1098** [comment]
https://github.com/tterrag1098/CustomThings/wiki/Getting-Started

**Comment by jtrent238** [comment]
I Dont Understand that
