### ISSUE TITLE
[Feature Request]: Make Custom Crops? 

### ISSUE THREAD

**Issue by mariodk** [tterrag1098/CustomThings#25]
be able to make the crops with custom Seed/Wheat for it(Wheat as what the seed drop once fully grown like use a Custom item from this mod as a Wheat)
& they support mods with auto planeters/harvesters(like minefactory reloaded/EnderIO)

and turn off/on bonemeal use on them
and how fast they can grow

**Comment by tterrag1098** [comment]
http://minecraft.curseforge.com/projects/kitchencraft

**Comment by mariodk** [comment]
is it possible to make a Kind of custom Magical crop out of this?
like the magical crop mod can grow  diamonds essence(& 9x diamonds essence = 1x diamond)/other resources

**Comment by tterrag1098** [comment]
Sure. Use KitchenCraft to add the crops, and CustomThings to add the essence items.
