### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by Fortist** [tterrag1098/CustomThings#26]
For a lot of people, learning how to do something isnt as simple as "Read the wiki" There are different types of learning, and maybe through reading some people can understand how to create whatever they need to create. However, for me at least, Reading the wiki over again will not magically show me how to create most of the stuff in the mod. Hence, examples.
THAT IS:
]
"name" Fuck this shit block
"hardness" 9999
"drops" Dildos
[
Etc etc.

I know Im on the right track, as a ton of mods have similar styles, but at least for a chunk of them they have extensive documentation and examples. I love Minetweaker since it has written examples that work.
Im pretty sure I know what to do, but reading tons of text with no examples just burns me out and Im probably gonna try it later or just straight up use other mods.

**Comment by tterrag1098** [comment]
There are written templates if you read this page https://github.com/tterrag1098/CustomThings/wiki/Getting-Started
