### ISSUE TITLE
A Little Help Please.

### ISSUE THREAD

**Issue by Cazadorsniper** [tterrag1098/CustomThings#27]
I have no idea what I'm doing wrong xD.
Crash: http://pastebin.com/yTNfN6Kj
Item json: http://pastebin.com/mpR5in15
Block json: http://pastebin.com/He1JgnUV

**Comment by tterrag1098** [comment]
`oreDictNames` is an array. Use it like so:

```
"oreDictNames": ["name1", "name2"]
```

**Comment by tterrag1098** [comment]
Also, your syntax for drops array is wrong. just use [] don't put quotes around it.

**Comment by Cazadorsniper** [comment]
ok thanks
