### ISSUE TITLE
Anmated textures

### ISSUE THREAD

**Issue by Cronosus** [tterrag1098/CustomThings#28]
Hello
is there way, to make animated textures for items/blocks?

thanks

**Comment by tterrag1098** [comment]
The vanilla way should work fine

**Comment by Cronosus** [comment]
vanilla way?

**Comment by tterrag1098** [comment]
http://minecraft.gamepedia.com/Resource_pack#Animation

**Comment by Cronosus** [comment]
i aready tried that, and not working for me.
then i post this isssue...

**Comment by tterrag1098** [comment]
That would have been some useful information. I think I might know why it doesn't work.

**Comment by tterrag1098** [comment]
Fixed via 20563f853a4609a079bf2ed0929196153f834092

**Comment by Cronosus** [comment]
thanks
working now. :)
