### ISSUE TITLE
[Help Wanted] So confused, wiki is not helpful much

### ISSUE THREAD

**Issue by jawsawn** [tterrag1098/CustomThings#3]
With this modification, that record making is the thing I need. I could able to use other mods (that has json lang) like Quadrum, Minetweaker but I have no idea how to use this one. Can you please add some examples in the wiki? Also can you help me with adding a simple disc? an example maybe?

keep the good work!

**Comment by tterrag1098** [comment]
If the wiki is confusing you, make sure you have read https://github.com/tterrag1098/CustomThings/wiki/Getting-Started and everything that page links to. It's very important for understanding the rest.

**Comment by jawsawn** [comment]
I did. But still couldn't understand it. Can you make some example codes like Quadrum did? 
like this page at the bottom "Example File": https://github.com/dmillerw/Quadrum/wiki/Items
