### ISSUE TITLE
Issue Creating items

### ISSUE THREAD

**Issue by DemonBigj781** [tterrag1098/CustomThings#32]
When i was trying to create a tool and two recipes i got this crash error op on instalization.
http://pastebin.com/iEf5AwSd

if there is any flaws in the json file can you also cheak that out.

https://drive.google.com/open?id=0B3x8mF_jqsd8bzYzNExaeUpCYjg

**Comment by tterrag1098** [comment]
oreDictNames is an array.

In your customTools.json you have `"oreDictNames":"toolMultitool",`

This should be `"oreDictNames": ["toolMultitool"],`

**Comment by DemonBigj781** [comment]
i tried that and still got the error
