### ISSUE TITLE
[1.7.10]Crash on Initializing Game

### ISSUE THREAD

**Issue by Lyl4c** [tterrag1098/CustomThings#34]
Crash report: http://pastebin.com/XNEcjEmL
Custom Block Config: http://pastebin.com/A6NcvQ8t
lang file: http://pastebin.com/QHrih9Su

minecraft 1.7.10
forge 10.13.4.1614
custom mod pack

I am trying to create 5 custom blocks using what the wiki provides as best as I can. Using this tool:
http://json.bloople.net/
the json code seems to be right. There doesn't seem to be examples of custom block code anywhere on google except the examples for creating items, but its slightly different than how custom blocks are made.

Textures for these blocks are in the icons folder.

**Comment by tterrag1098** [comment]
Line 82 has a trailing comma. I believe this is causing the crash.

**Comment by Lyl4c** [comment]
_facepalm_ 
its loading up find now. i guess i was too tired at the time to see that.
i fixed the lang file while i was at it. the blocks are showing the correct name, but now the textures for the blocks are missing. Whats the file structure for the block textures?

**Comment by tterrag1098** [comment]
https://github.com/tterrag1098/CustomThings/wiki/Adding-Icons-and-Lang-Files

> To add an icon for an item, simply throw a png file called itemName.png (itemName being the "name" field you defined for your food) in the /icons directory.

It is the same for blocks.

**Comment by EverNife** [comment]
Lyl4c can you give me your config folder in zip for me to see how it is

Just the customthings please :D

**Comment by Lyl4c** [comment]
https://github.com/Lyl4c/customthings-configs

this is the link to my customthings configs.

**Comment by tterrag1098** [comment]
It's worth noting that you don't need to include fields which are default. Such as you have minXp and maxXp set to 0, which is the default. So you could just leave them out.

**Comment by EverNife** [comment]
Lyl4c, to fix your texture, replace the

> "textureMap": []

with 

> "textureMap": null

**Comment by Lyl4c** [comment]
Thanks that did fix it.
