### ISSUE TITLE
Better Crash-Reports

### ISSUE THREAD

**Issue by EverNife** [tterrag1098/CustomThings#37]
Is there a way to implement those crash-reports, like something telling what is missing or is wrong?

For exemple, "missing name entry", "missing durability entry", or warning about wrong location of dots

> " . , [ {

**Comment by Maxwelljones** [comment]
use http://jsonlint.com/ to check your json maybe?

**Comment by EverNife** [comment]
Cause sometimes is not the syntax who is wrong, is that you are missing something...

Like the exemple of the wiki over here: https://github.com/tterrag1098/CustomThings/issues/35#issuecomment-241526478

As well as your exemple over here: https://github.com/tterrag1098/CustomThings/issues/41

**Comment by evernife** [comment]
As well as your exemple over here:

https://github.com/tterrag1098/CustomThings/issues/41

**Comment by tterrag1098** [comment]
A missing entry is never an error. I have defaults for _almost_ every single field for every type of custom object. Most errors given to me are in fact JSON syntax errors, which I can do nothing about as that code is out of my control. A site like the one @Maxwelljones linked is a great resource for this.

**Comment by Eufranio** [comment]
You could implement a in-game json parser, like MyTown2 does, and don't let the game to crash...

**Comment by tterrag1098** [comment]
@Eufranio That would be a massive amount of work to recreate something that already exists. I could prevent the game from crashing, but then what? Your items just don't exist?

**Comment by Eufranio** [comment]
Like MineTweaker, it just don't make the changes and specify the error, then you can fix it yourself without reporting in a github repo to get help...

**Comment by EverNife** [comment]
http://jsonlint.com/ seems fine at all...
