### ISSUE TITLE
[1.7.10]Meta Replace Bug

### ISSUE THREAD

**Issue by Lyl4c** [tterrag1098/CustomThings#38]
Screenshots: http://imgur.com/a/C603p
Custom Block Config: http://pastebin.com/MB1AfZ6N
Lang File: http://pastebin.com/7zNuL5mN

minecraft 1.7.10
forge 10.13.4.1614
custom mod pack

From a meta value of 0 to 15, the mod will move back to 0 of the same block id and replace 0 with a new block before creating a new id for another set of meta values. 

That's as best as I could explain it simply. the very first block in the bottom left there (the last is in the top right) is replaced by what should have been 2216/0 and not 2208/0. It used to be Asteroid Rock which is the first in both the config and the lang files. Its the same for that umber silver ore there that should have been the moon mithril ore.

edit: just a few minutes of organizing ores here and I found out there's 2 mithril ores here that are either not where they're supposed to be or is replaced by another block.

**Comment by tterrag1098** [comment]
Thanks, easy fix. Sorry about that one.
