### ISSUE TITLE
[1.10.2] Crash when adding a block

### ISSUE THREAD

**Issue by MechWarrior99** [tterrag1098/CustomThings#39]
Trying to add a block I get [this](http://pastebin.com/9DA4d6gb) crash
here is my script:
{"data":
    [
        {
        "name": "ambientStone",
        "harvestLevel": 3,
        "hardness": 0.3f,
        "toolType": "pickaxe"
        }
    ]
}

**Comment by Cazadorsniper** [comment]
if still having this issue remove the f on hardness

**Comment by MechWarrior99** [comment]
Ah, thanks.
But it turns out that there is a larger issue that all blocks need a model file, so that needs to be added before it is really usable.
