### ISSUE TITLE
New Item Crash

### ISSUE THREAD

**Issue by Maxwelljones** [tterrag1098/CustomThings#41]
Getting a crash trying to add one item into customitems.json

```
{
    "data": [{
        "name": "Todabonium Ingot",
        "container": "null",
        "oreDictNames": ["todabonium"],
        "maxStackSize": "64",
        "burnTime": "0",
        "rarity": "common",
        "enchanted": "true"
    }]
}
```

Crashlog: [Pastebin](http://pastebin.com/k3Z7ne9h)
[OpenEye crash report](https://openeye.openmods.info/crashes/4cb07de6d93f808d0abd8d8bd2d14368)
CustomThings-MC1.7.10-0.0.3-55
EnderCore-1.7.10-0.2.0.39_beta

Can you help please ?

**Comment by Maxwelljones** [comment]
@evernife do you mean I am missing something? Would be great if you could brighten my darkness :)

**Comment by evernife** [comment]
That is the point of the BetterCrash report...

Anyway... I recommend you use this... [CustomItems](https://mods.curse.com/mc-mods/minecraft/224312-customitems#t1:other-downloads)

(Use the ***Meta Mod - Custom Items 1.0.9***)

Wiki of the CustomItems: http://customitems.otho.me/
You will need mine-tweaker to create recipes, and for the textures, you can open the .jar file am drag them into the ressources... i found that plugin more easy (Docummented) than this one T.T

**Comment by tterrag1098** [comment]
The issue is the `"container": "null"` line, this line is unnecessary. By default there is no container item. Just remove it and it should work fine.

@evernife I have no issue with alternatives, but advertising them on my issue tracker is a bit rude, in my opinion.

**Comment by EverNife** [comment]
my bad, sorry T,T

**Comment by Maxwelljones** [comment]
Thanks @tterrag1098 works great, thank you!

@evernife sorry what you suggested doesn't work. The version you linked crashes when mining nether quartz, the newer version don't create any item. I moved away and found tterag's mods which are just great ;=)

**Comment by tterrag1098** [comment]
@Maxwelljones it was my fault, the example did that. I believe "null" should work, might be a bug in EnderCore.
