### ISSUE TITLE
Naming Issue

### ISSUE THREAD

**Issue by Maxwelljones** [tterrag1098/CustomThings#42]
When I use the code:

```
    "data": [{
        "name": "Todabonium Ingot",
        "oreDictNames": ["todabonium"],
        "maxStackSize": "64",
        "burnTime": "0",
        "rarity": "common",
        "enchanted": "true"
    }]
```

I get a item name issue:
Item is called: item."name".name I would wish it would only write "name" (see image below)
Am I doing something wrong? I get the same for every item I create with the mod.
![image](https://cloud.githubusercontent.com/assets/3750700/19183416/73c45378-8c78-11e6-9e2e-f3ee6d31261d.png)

**Comment by tterrag1098** [comment]
As this mod has full translation support,  you must add language entries for your items. See https://github.com/tterrag1098/CustomThings/wiki/Adding-Icons-and-Lang-Files .

I would recommend the "name" field being something simpler and without spaces, but it is not a strict requirement.

**Comment by Maxwelljones** [comment]
Now I understand and it fully makes sense. Thanks @tterrag1098
