### ISSUE TITLE
armor cap?

### ISSUE THREAD

**Issue by Boter316** [tterrag1098/CustomThings#48]
no matter how I recode the armor it will not resist more than 127 damage, then it all applies at once, is this an intentional feature?

also, I think it would be neat if you could add thaumcraft support for things like Vis Discounts, or for revealing on helmets

**Comment by tterrag1098** [comment]
I believe that is a vanilla limitation. I don't impose any limits on the values.

**Comment by Boter316** [comment]
close this, I figured out the problem, I was a derp and didn't sync up the numbers properly
