### ISSUE TITLE
custom render size and offset?

### ISSUE THREAD

**Issue by Boter316** [tterrag1098/CustomThings#52]
this one might be a little easy actually, allowing for a custom render size of an item and a custom offset/rotation of said tool/item

**Comment by tterrag1098** [comment]
Sure, that can be done with models.

**Comment by Boter316** [comment]
I was using the 1.7.10, I didn't seea custom Model option, or has support for 1.7.10 gone now?

**Comment by tterrag1098** [comment]
1.7.10 is 3 years old now, I don't have the time to maintain that.

**Comment by Boter316** [comment]
fair enough, then go ahead and close all my suggestions, they were all for 1.7.10, also is it in a new spot? the curseforge only shows 1.7.10?
