### ISSUE TITLE
[Suggestion] More options for custom items

### ISSUE THREAD

**Issue by BBoldt** [tterrag1098/CustomThings#6]
Basically, stuff like this:
https://github.com/dmillerw/Quadrum/wiki/Items

Most specifically, the following:
- burn-time
- ore-dictionary
- lore

Maybe a few basic food related ones, nothing crazy:
- isfood (true or false)
- consume-effect
- consume-duration
- hunger
- saturation

**Comment by tterrag1098** [comment]
Food stuff is not being done. Use KitchenCraft for that. Lore was already possible with the .tooltip lang entry. Oredict has oreDictNames. Burn time was added under #9.
