### ISSUE TITLE
[Bug] Harvest Level not working correctly

### ISSUE THREAD

**Issue by SnowShock35** [tterrag1098/CustomThings#8]
Hi,

Using the following setup, the harvest level field for blocks isn't correctly working in the game.

---

**Basic Information:**
- Minecraft 1.7.10
- Forge 10.13.4.1448

---

**Mod List:**
- CustomThings MC1.7.10-0.0.2-31
- ttCore MC1.7.10-0.1.1-78

---

**File Example:**
_customBlocks.json_
http://paste.ee/p/Au5KR

**Comment by tterrag1098** [comment]
Fixed via https://github.com/tterrag1098/CustomThings/commit/b87b71c4ecaa5312247e15766af9152cef8f6190
