### ISSUE TITLE
[Suggestions] A collection of suggestions for CustomThings

### ISSUE THREAD

**Issue by SnowShock35** [tterrag1098/CustomThings#9]
Hi,

I've used CustomThings a little bit now and I think a few additional fields in the different jsons and one or two other features would make the mod go along way. This somewhat respects aspects of #4 #6 and #7 but, with a few alterations/elaborations on them and one or two other suggestions.

**Blocks**

Additional fields such as...
- Light level - Light level of the block i.e. Glowstone
- Transparency - Can X item be placed on it, does it effect beacon beam and whether it can be seen through i.e. glass or ice
- Gravity - Does it fall when there are no blocks bellow it i.e. sand, gravel and anvils
- Max Stack Size - What it's max stack size is. If it's a 1 or 16 like enderpearls or buckets
  *****

**Items**

Additional Fields such as...
- Burn Time - How long it burns for in a furnace
- Mob drop - Is it dropped by a mod, what mob, chance ect i.e. Gunpowder=Creeper
- Max Stack Size - What it's max stack size is. If it's a 1 stack item or 16 like enderpearls or buckets

---

**Misc**
- When the mod creates items or blocks it always creates a new id and never uses metadata unless, a field for metadata is set to
- Fluids for the mod <--- Saves me adding JSONAbles by @jaredlll08  :stuck_out_tongue: 

---

Will continue to add if I think of more :wink:

**Comment by jaredlll08** [comment]
"Fluids" traitor :(
Giving unlocalized names would ness wit the metadata aspect of it
Dog food, iirc you need a different class for this, is doable.

**Comment by SnowShock35** [comment]
@jaredlll08 Stop your whining :stuck_out_tongue:

**Comment by jaredlll08** [comment]
Then stop your traitoring :P

**Comment by SnowShock35** [comment]
@jaredlll08 NEVAH! :stuck_out_tongue_winking_eye:

**Comment by jaredlll08** [comment]
_gets the blow torch_

**Comment by tterrag1098** [comment]
Everything in this list should now be done, with the exception of a few.

I will not be changing how IDs/meta are allocated, this is central to the algorithms I use to add blocks+items. It also helps save on IDs massively. I understand that metadata can shift, I plan to solve this in the future.
